config/routes.rb
Rails.application.routes.draw do
root 'home#index'
  get 'home/index'
  get 'home/aboutus'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user1.rb
class User1 < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def aboutus
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
<div class="container"> 
<!-- Brand and toggle get grouped for better mobile display --> 
<div class="navbar-header"> 
<button type="button" class="navbar-toggle collapsed" data-
toggle="collapse" data-target="#bs-example-navbar-collapse-1"> 
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span> 
<span class="icon-bar"></span> 
<span class="icon-bar"></span> 
</button> 
<a class="navbar-brand" href="#">Brand</a> 
</div> 
<!-- Collect the nav links, forms, and other content for toggling --> 
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> 
<ul class="nav navbar-nav navbar-right"> 
<li><%= link_to 'Home', root_path %></li> 
<li><%= link_to 'About Me', home_aboutus_path %></li> 
</ul> 
</div><!-- /.navbar-collapse --> 
</div><!-- /.container-fluid --> 
</nav> 

app/views/home/aboutus.html.erb
<h1>About me </h1>
<p>My name is aditya and hi there </p>

app/views/home/index.html.erb
<div class = "jumbotron">
 
<h1>Welcome to my app</h1>
<p>This is gonna be beautiful</p>
<%= link_to 'Home' , root_path , class: 'btn btn-default' %>
<%= link_to 'About us',  home_aboutus_path , class: 'btn btn-default' %> 

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'home/header' %>
<div class ="container" >
<% flash.each do |name,msg| %>
<%= content_tag“(:div, msg, class: "alert alert-info") %> 
<%end%>
<%= yield %>
</div>
</body>
</html>